### ISSUE TITLE
A regex?

### ISSUE THREAD

**Issue by sethgrid** [badoux/checkmail#1]
You link to a document that says don't use a regex, and then use a regex. At work, we send about 1.6 billion emails a day. We agree with the article. Search for @.

**Comment by badoux** [comment]
Yes, a regexp is not enought, that's why the pkg provide a method to validate the domain and the mailbox. I prefer to follow the advice of the W3C for the regexp, which gives us a simple regexp, a little more than just '@' : https://www.w3.org/TR/html5/forms.html#valid-e-mail-address
