### ISSUE TITLE
Panic when trying to ValidateFormat a@b.c

### ISSUE THREAD

**Issue by SpareShade** [badoux/checkmail#11]
Hi!
Thank you for this great library!
Could not see that this was already reported. 
The library panics if an email with "short" length is provided. ie
```go
err := checkmail.ValidateFormat("a@b.c")
```
```go
panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by XescuGC** [comment]
I can not reproduce this error on `master` with last  commit https://github.com/badoux/checkmail/commit/d0a759655d62bcdc95c50a0676f3e9702ed59453

**Comment by heikki-john** [comment]
Seems that panic also with "a@gmaili.com" or "a@gmail.fi"

**Comment by xescugc** [comment]
Could it be that you are also calling the `checkmail.ValidateHost(email)`?

**Comment by heikki-john** [comment]
Ah Jes. That validateHost is that what causes that panic. Is there issue about that yet?

**Comment by xescugc** [comment]
Nope, but I've found the error on the `ValidateHost` haha
