### ISSUE TITLE
Supposedly invalid addresses are passing validation

### ISSUE THREAD

**Issue by byxor** [badoux/checkmail#21]
I've found a list of [supposedly invalid email addresses](https://blogs.msdn.microsoft.com/testing123/2009/02/06/email-address-test-cases/).

Apparently they violate [rfc2822](http://www.ietf.org/rfc/rfc2822.txt).

Some of them are passing validation in checkmail.

```go
invalidEmails := []string {
    ".email@example.com",
    "email.@example.com",
    "email..email@example.com",
    "email@example",
    "email@example.web",
    "email@111.222.333.44444",
    "email@example..com",
    "Abc..123@example.com",
}

// ^ These are all considered valid by checkmail,
```

I think it has something to do with leading/trailing/double period characters.

Are these meant to be passing validation or not?

**Comment by dansku** [comment]
@byxor I agree, the regex used is not valid, along with many I found online.
