### ISSUE TITLE
Change regex to match all the email addresses according to RFC 3696

### ISSUE THREAD

**Issue by younisshah** [badoux/checkmail#22]
According to [RFC 3696](https://tools.ietf.org/html/rfc3696#section-3), Application Techniques for Checking and Transformation of Names, the example email address used in the first example of README.md is apparently a valid email address.

Similarly, these are all valid email addresses:

- Abc\@def@example.com
- Shah\ Younis@example.com
- younis.\\Shah@example.com
- "Abc@def"@example.com
- "Younis Shah"@example.com
- customer/department=shipping@example.com
- $A12345@example.com
- !def!xyz%abc@example.com
- _somename@example.com

For more, check this [I Knew How To Validate An Email Address Until I Read The RFC](https://haacked.com/archive/2007/08/21/i-knew-how-to-validate-an-email-address-until-i.aspx/)

**Comment by AdeSupriyadi** [comment]
used this package
x@x 
return valid
