### ISSUE TITLE
Please tag a new release and start using Semantic Versioning

### ISSUE THREAD

**Issue by KateGo520** [badoux/checkmail#29]
I found that this project already [supports Go modules](https://github.com/badoux/checkmail/blob/master/go.mod). But sadly, the [tags](https://github.com/badoux/checkmail/tags) doesn't follow [Semantic Versioning](https://semver.org), which means that all tags of this project will be ignored by Go modules and replaced by pseudo-versions, go get acts weirdly when tags are not in that form. It would be great to have the tagged release be named in the format vX.X.X format so that go mod can read it. 
```
	github.com/badoux/checkmail v0.0.0-20200623144435-f9f80cb795fa
```
Else the mod file shows something like `github.com/badoux/checkmail v0.0.0-20200623144435-f9f80cb795fa` which is not very readable and difficult to upgrade. It’s hard to verify which version is in use. This is not conducive to version control

So, I propose this project to follow Semantic Versioning in future versions. For example, `v1.0.1`, `v2.0.0`, `v3.1.0-alpha`, `v3.1.0-beta.2`etc.

**Comment by KateGo520** [comment]
@badoux  Could you help me review this issue? Thx :p

**Comment by badoux** [comment]
It's done @KateGo520 , thanks !

**Comment by KateGo520** [comment]
@badoux  Thank you for your contribution！
