### ISSUE TITLE
New release unable to build due to escape sequence

### ISSUE THREAD

**Issue by truescotian** [badoux/checkmail#33]
FYI -- Did a pull on master and now running into this after building:
![image](https://user-images.githubusercontent.com/14235977/111516681-ef6dd800-8732-11eb-877b-58c39f42be1c.png)

**Comment by badoux** [comment]
@truescotian  Sorry for the bug. It was introduced by the latest PR #31

**Comment by badoux** [comment]
Should be fixed now
