### ISSUE TITLE
always got error althougt email is real 

### ISSUE THREAD

**Issue by goldalworming** [badoux/checkmail#4]
Hi, I always got Error 421 Cannot connect to SMTP server 74.125.68.26 (74.125.68.26:25), connect error 10060 althought it's valid email

Do you have any ideas to fix it

**Comment by goldalworming** [comment]
Code: 421, Msg: 421 Cannot connect to SMTP server 74.125.68.27 (74.125.68.27:25), connect error 10060

**Comment by badoux** [comment]
Hi, 

Can you give me the email so i can test with it ? 

Thks

**Comment by badoux** [comment]
BTW if this is a SMTP error i can't do nothing. You have to treat this email as valid and send a mail to the user to validate the mail. This library can't validate an email at 100%, it should be used in addition to the send of an activitation email.

**Comment by goldalworming** [comment]
should use certain smtp setting to make this library works?
