### ISSUE TITLE
Error with same provider

### ISSUE THREAD

**Issue by amatig** [badoux/checkmail#5]
Hi i have an error to check same provider host like:
gmx.de, net or com
freenet.de, web.de, ecc

error:

gmx.net (mxgmx002) Nemesis ESMTP Service not available
No SMTP service
Bad DNS PTR resource record.

or

freenet.de 550 inconsistent or no DNS PTR record for 95.110.198.3

**Comment by badoux** [comment]
Hi,

This error occurs when your host doesn't have a DNS PTR record. 
(https://www.siteground.com/kb/what_is_a_ptr_record_and_how_to_add_one/)

They are smtp errors, this is not the responsibility of this pkg, this pkg can't deal with them.
